### ISSUE TITLE
Wrong time of SG on Nightscout with minimedcarelink source

### ISSUE THREAD

**Issue by skritland** [nightscout/nightscout-connect#16]
Hello,

I've started using nightscout with nightscout-connect plugin using docker. I've configured everything and no matter what combination of timezones I'm setting, I get always shifted data. It looks like mesurements time from CareLink is in local time but is treated like UTC time. Below more information:

docker-compose.yaml:
```
nightscout:
    image: nightscout/cgm-remote-monitor:latest_dev
    container_name: nightscout
    environment:
      TZ: Europe/Warsaw
      TIME_FORMAT: 24
      MONGO_CONNECTION: mongodb://mongo:27017/nightscoutdb
      API_SECRET: SECRET
      BG_HIGH: 200
      BG_LOW: 70
      BG_TARGET_TOP: 180
      BG_TARGET_BOTTOM: 70
      AUTH_DEFAULT_ROLES: readable devicestatus-upload
      ENABLE: careportal boluscalc food bwp cage sage iage iob cob basal ar2 rawbg pushover bgi pump openaps cors connect
      SHOW_FORECAST: openaps
      SHOW_PLUGINS: careportal openaps pump iob sage cage
      CUSTOM_TITTLE: Nightscout
      DISPLAY_UNITS: mg/dl
      INSECURE_USE_HTTP: "true"
      CONNECT_SOURCE: minimedcarelink
      CONNECT_CARELINK_REGION: eu
      CONNECT_COUNTRY_CODE: pl
      CONNECT_CARELINK_USERNAME: user
      CONNECT_CARELINK_PASSWORD: pass
    ports:
      - 1337:1337
    depends_on:
      - mongo
    volumes:
      - ./nightscout:/var/opt/ssl/:ro
    restart: unless-stopped

  mongo:
    image: mongo:4.4.23
    container_name: mongo
    environment:
      TZ: Europe/Warsaw
    volumes:
      - ./mongo/data:/data/db
    restart: unless-stopped
```
extract from docker logs:
```
   {
      lastSGTrend: 'UP',
      type: 'sgv',
      sgv: 174,
      date: 1691354760000,
      dateString: '2023-08-06T20:46:00.000Z',
      device: 'nightscout-connect://minimedcarelink/NGP',
      trend: 2,
      direction: 'SingleUp'
    }
  ],
  devicestatus: [
    {
      created_at: '2023-08-06T18:47:18.807Z',
      lastMedicalDeviceDataUpdateServerTime: 1691347606617,
      device: 'nightscout-connect://minimedcarelink/NGP',
      uploader: [Object],
      connect: [Object],
      pump: [Object]
    }
  ],
  treatments: []
}
got data-received event, requesting reload
```

![obraz](https://github.com/nightscout/nightscout-connect/assets/1151837/f0df48fc-f71e-4a9c-9683-643bc25e4acb)
